<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-03T02:25:54 EDT" name="Suite" finished-at="2025-04-03T02:26:52 EDT" duration-ms="58197">
    <groups>
    </groups>
    <test started-at="2025-04-03T02:25:54 EDT" name="Two" finished-at="2025-04-03T02:26:33 EDT" duration-ms="39001">
      <class name="tests.TwoTest">
        <test-method signature="testTwo()[pri:0, instance:tests.TwoTest@7b94089b]" started-at="2025-04-03T02:25:54 EDT" name="testTwo" finished-at="2025-04-03T02:26:11 EDT" duration-ms="17675" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTwo -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:tests.TwoTest@7b94089b]" started-at="2025-04-03T02:26:11 EDT" name="closeBrowser" finished-at="2025-04-03T02:26:33 EDT" duration-ms="21256" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- tests.TwoTest -->
    </test> <!-- Two -->
    <test started-at="2025-04-03T02:25:54 EDT" name="Four" finished-at="2025-04-03T02:26:49 EDT" duration-ms="54966">
      <class name="tests.FourTest">
        <test-method signature="testFour()[pri:0, instance:tests.FourTest@e54303]" started-at="2025-04-03T02:25:54 EDT" name="testFour" finished-at="2025-04-03T02:26:08 EDT" duration-ms="14481" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at tests.FourTest.testFour(FourTest.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFour -->
      </class> <!-- tests.FourTest -->
    </test> <!-- Four -->
    <test started-at="2025-04-03T02:25:54 EDT" name="Three" finished-at="2025-04-03T02:26:52 EDT" duration-ms="58197">
      <class name="tests.ThreeTest">
        <test-method signature="testThree()[pri:0, instance:tests.ThreeTest@79c7532f]" started-at="2025-04-03T02:25:54 EDT" name="testThree" finished-at="2025-04-03T02:26:08 EDT" duration-ms="13972" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testThree -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:tests.ThreeTest@79c7532f]" started-at="2025-04-03T02:26:08 EDT" name="closeBrowser" finished-at="2025-04-03T02:26:52 EDT" duration-ms="44158" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- tests.ThreeTest -->
    </test> <!-- Three -->
  </suite> <!-- Suite -->
</testng-results>
